INSERT INTO mission(theme_id, city_id, country_id, Title, short_Description, Description, Start_Date, end_Date, mission_type, status, Organization_Name, Organization_Detail, availability)
VALUES
(1, 2, 3, 'Teaching English in Rural Schools', 'Volunteers will teach English to children in rural schools', 'We are looking for volunteers to teach English to underprivileged children in rural schools. Volunteers should have experience in teaching English as a second language and be passionate about making a difference in the lives of these children.', '2023-03-01', '2023-05-30', 'Time', 1, 'Teach for Change', 'Teach for Change is a non-profit organization that aims to provide quality education to underprivileged children.', 'weekly'),
(2, 3, 4, 'Building Homes for the Homeless', 'Volunteers will build homes for the homeless', 'We are looking for volunteers to help us build homes for the homeless. Volunteers will be responsible for tasks such as laying bricks, mixing cement, and painting walls. No prior experience is required, but volunteers should be physically fit.', '2023-04-01', '2023-06-30', 'Goal', 1, 'Habitat for Humanity', 'Habitat for Humanity is a non-profit organization that aims to provide affordable housing to low-income families.', 'daily'),
(3, 4, 5, 'Animal Welfare and Rescue', 'Volunteers will work with animals in a shelter', 'We are looking for volunteers to help us take care of animals in our shelter. Volunteers will be responsible for tasks such as feeding the animals, cleaning their cages, and taking them for walks. No prior experience is required, but volunteers should be comfortable working with animals.', '2023-05-01', '2023-08-30', 'Time', 1, 'Animal Welfare Society', 'Animal Welfare Society is a non-profit organization that works towards the welfare and protection of animals.', 'weekend'),
(4, 5, 6, 'Teaching Computer Skills to Senior Citizens', 'Volunteers will teach computer skills to senior citizens', 'We are looking for volunteers to teach computer skills to senior citizens. Volunteers should have experience in teaching basic computer skills such as browsing the internet, sending emails, and using social media.', '2023-06-01', '2023-08-31', 'Time', 1, 'SeniorNet', 'SeniorNet is a non-profit organization that aims to help senior citizens learn computer skills and stay connected with their loved ones.', 'weekly'),
(5, 6, 7, 'Environmental Cleanup Drive', 'Volunteers will participate in an environmental cleanup drive', 'We are looking for volunteers to participate in an environmental cleanup drive. Volunteers will be responsible for tasks such as picking up litter, planting trees, and creating awareness about environmental conservation.', '2023-07-01', '2023-07-31', 'Goal', 1, 'Greenpeace', 'Greenpeace is a non-profit organization that works towards environmental conservation and protection.', 'daily')




INSERT INTO mission ("theme_id", "city_id", "country_id", "Title", "short_Description", "Description", "Start_Date", "end_Date", "mission_type", "status", "Organization_Name", "Organization_Detail", "availability")
VALUES (1, 2, 3, 'Community Clean-Up Day', 'Join us in cleaning up the local park', 'We will provide gloves, trash bags, and other necessary equipment. Just bring yourself and your enthusiasm!', '2023-03-25 09:00:00', '2023-03-25 12:00:00', 'Time', 1, 'Green Earth Organization', 'We are a non-profit dedicated to preserving the environment', 'daily');

INSERT INTO mission ("theme_id", "city_id", "country_id", "Title", "short_Description", "Description", "Start_Date", "end_Date", "mission_type", "status", "Organization_Name", "Organization_Detail", "availability")
VALUES (2, 1, 4, 'Feed the Homeless', 'Help us provide meals to those in need', 'We will be serving hot meals to the homeless population in the city. Volunteers are needed to help prepare and distribute the meals.', '2023-04-02 10:00:00', '2023-04-02 14:00:00', 'Time', 1, 'Hope for the Homeless', 'We are a charity organization working to end homelessness', 'weekly');

INSERT INTO mission ("theme_id", "city_id", "country_id", "Title", "short_Description", "Description", "Start_Date", "end_Date", "mission_type", "status", "Organization_Name", "Organization_Detail", "availability")
VALUES (3, 5, 1, 'Plant Trees for the Future', 'Help us create a greener world', 'We will be planting trees in the city park to help combat climate change and provide a healthier environment for future generations.', '2023-04-22 09:00:00', '2023-04-22 12:00:00', 'Time', 1, 'Green World Initiative', 'We are a global organization dedicated to environmental conservation', 'week-end');

INSERT INTO mission ("theme_id", "city_id", "country_id", "Title", "short_Description", "Description", "Start_Date", "end_Date", "mission_type", "status", "Organization_Name", "Organization_Detail", "availability")
VALUES (1, 2, 3, 'Volunteer at a Local Animal Shelter', 'Help care for furry friends in need', 'We need volunteers to help us care for animals at the local shelter. Duties include walking dogs, cleaning cages, and providing love and attention to our furry residents.', '2023-04-15 13:00:00', '2023-04-15 16:00:00', 'Time', 1, 'Paws for a Cause', 'We are a non-profit organization working to find loving homes for abandoned animals', 'monthly');